// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Suave.Swagger")>]
[<assembly: AssemblyProductAttribute("Suave.Swagger")>]
[<assembly: AssemblyDescriptionAttribute("This is an extension for Suave.io with some REST tools and Swagger documentation helpers")>]
[<assembly: AssemblyVersionAttribute("2.1.0")>]
[<assembly: AssemblyFileVersionAttribute("2.1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Suave.Swagger"
    let [<Literal>] AssemblyProduct = "Suave.Swagger"
    let [<Literal>] AssemblyDescription = "This is an extension for Suave.io with some REST tools and Swagger documentation helpers"
    let [<Literal>] AssemblyVersion = "2.1.0"
    let [<Literal>] AssemblyFileVersion = "2.1.0"
